### ISSUE TITLE
Metrics and config for Docker Agent

### ISSUE THREAD

**Issue by joente** [oversight/dockeragent#1]
As this will be an agent, a token and environment uuid is required for authentication.

Prefix env variable with "OSDA" (OverSightDockerAgent)

```
OSDA_TOKEN
OSDA_ENVIRONMENT_UUID
OSDA_HOST_UUID
OSDA_API_URI
```

Each check could also have an optional `*_INTERVAL` environment variable which tells the probe how often to check. (default to 300 seconds). We could accept `0` seconds to disable the check. 

An example, first check could be `CheckSystem` with env var `OSDA_CHECK_SYSTEM_INTERVAL`.

For development:, the uri should be `https://webserver.development.oversig.ht/api/` (last `/` should be optional)

Since this will be an Agent, the API (https://docs.oversig.ht/api/metadata/set-type-definition/) is required to create the docker agent metrics.

For Inserting data: https://docs.oversig.ht/api/data/insert-data/

The current docker probe has four checks, each with one or more types:

```
CheckSystem
    system
CheckContainers
    netio
    ...
CheckImages
    ...
CheckNetstat
    ...
```

Let's first start with making the `/info` docker api call and review the result. (the /info call contains the result for CheckSystem)

**Comment by joente** [comment]
Check System: (`/info` api call)

- Check name: `CheckSystem`
- Type name: `system`
- Item name: (only a single item, we can use `Name` as `name`. So not `system` as earlier discussed.

Source | Metric Name | Type | example
--------- | ------------------| -------| ------------
"ID" | id | str |  "NN2P:6M7W:POJ4:3NLC:PNZE:2MBH:YUFX:DDYG:KGRM:OGML:QAIH:RPN3"
"Containers" | containers | int | 1
"ContainersRunning" | containersRunning | int | 1
"ContainersPaused" | containersPaused | int | 0
"ContainersStopped" | containersStopped | int | 0
"Images" | images | int | 39
"Driver" | driver | str | "overlay2"
"SystemStatus" | systemStatus | str | "None"
"MemoryLimit" | memoryLimit | bool | true
"SwapLimit" | swapLimit | bool | false

**Comment by joente** [comment]
Check System: (`/info` api call)

Check name: CheckContainers
Type name: containers
Item name: Looking at the existing code, it seems there is always at least one name. so i think we can keep this name to identify the container, and we strip the first char.

Source | Metric name | Type | Example
-------- | ----------------- | ----- | -------------
"Id" | id | str | `"9d63834bc6edf6af53f41a83d25994b5a3e5015d0a496c7231dfd27cd63dfa2b"`
"Names" | name | str | Take the first name and strip the fist char. At least one name always exists. Example: `"redis'`
"Names" | names | str | Concat all the names. Example: `"[/redis]"`
"Image" | image | str | "redis"
"ImageID" | imageId | str | "sha256:40c68ed3a4d246b2dd6e59d1b05513accbd2070efb746ec16848adc1b8e07fd4"
"Command" | command | str | "docker-entrypoint.sh redis-server"
"Created" | created | int | 1649064285
"State" | state | str | "running"
"Status" | status | str | "Up 11 seconds"
"HostConfig/NetworkMode" | networkMode | "default" *(Only if HostConfig and NetworkMode exists)*

Type name: networks
Item name: container name (see above) combined with network name using an `_` underscore to concat.

Source | Metric name | Type | Example
--------- | ----------------- | ------- | -----------
Name+Key  | name | str | container name + key, example: `"redis_bridge"`
"NetworkID" | networkId | str | "e154247793bad6ff0688d5923b96e068c91a6aa60aa2b64c15574d541f5b2a68"
"EndpointID" | endpointId | str | "fc9bad810797f172d8427b6ff4197cf97bedc0f9d2187b58b9a17b916b874739"
"Gateway" | gateway | str | "172.17.0.1"
"IPAddress" | ipAddress | str | "172.17.0.2"


             "bridge":{
                "IPAMConfig":"None",
                "Links":"None",
                "Aliases":"None",
                "NetworkID":"e154247793bad6ff0688d5923b96e068c91a6aa60aa2b64c15574d541f5b2a68",
                "EndpointID":"fc9bad810797f172d8427b6ff4197cf97bedc0f9d2187b58b9a17b916b874739",
                "Gateway":"172.17.0.1",
                "IPAddress":"172.17.0.2",
                "IPPrefixLen":16,
                "IPv6Gateway":"",
                "GlobalIPv6Address":"",
                "GlobalIPv6PrefixLen":0,
                "MacAddress":"02:42:ac:11:00:02",
                "DriverOpts":"None"
             }


       "Ports":[
          {
             "IP":"0.0.0.0",
             "PrivatePort":6379,
             "PublicPort":6379,
             "Type":"tcp"
          }
       ],
       "Labels":{

       },
       "NetworkSettings":{
          "Networks":{

          }
       },
       "Mounts":[
          {
             "Type":"volume",
             "Name":"77e6080a1f11e9895953cd0ab0e154b5f4826729c86dbbf721e991d1d6b414f4",
             "Source":"",
             "Destination":"/data",
             "Driver":"local",
             "Mode":"",
             "RW":true,
             "Propagation":""
          }
       ]
    }
 ]

**Comment by joente** [comment]
Check Images  (`/images/json?all=false` api call)

Check name: CheckImages

**Type name**: images
Item name: Use the Id as Name


Source | Metric name | Type | Example
-- | -- | -- | --
Containers | containers | int |  -1 *(Why is this -1 ?? TODO: check docs)*
Created | created | int | 1647623610
Id | name | str | "sha256:5c4350efb04f9edbe8adc2673cf310cc20a1bc748f33b6fb12bd1a1c65ffce2d"
ParentId | parentId | str | "None"
RepoDigests | repoDigests | str | concat to single string, e.g: "[python@sha256:b1fdf84f, node@sha256:435df]"
RepoTags | repoTags | str | concat tags to single string, e.g: "[python:3.8]"
SharedSize | sharedSize | int | -1
Size | size | int | 911753678
VirtualSize | virtualSize | int | 911753678

**Comment by joente** [comment]
**CheckNetstat**

This is an overview for the dockerProbe CheckNetstat metrics:

![image](https://user-images.githubusercontent.com/6572730/163343200-016c6b45-1e6d-48dc-8066-e672bd154a38.png)

I think we can keep (almost) the same metric names.

Only type `connectioncounts` should be renames to `counts` and metric name `count` to `numConnections`

**Comment by AnjaBruls** [comment]
Metric info to set type definition:
```
{
  "probe": "dockerAgent",
  "check": "CheckSystem",
  "type": "system",
  "metrics": [
    {
      "name": "id",
      "dataType": "str"
    },
    {
      "name": "containers",
      "dataType": "int"
    },
    {
      "name": "containersRunning",
      "dataType": "int"
    },
    {
      "name": "containersPaused",
      "dataType": "int"
    },
    {
      "name": "containersStopped",
      "dataType": "int"
    },
    {
      "name": "images",
      "dataType": "int"
    },
    {
      "name": "driver",
      "dataType": "str"
    },
    {
      "name": "systemStatus",
      "dataType": "str"
    },
    {
      "name": "memoryLimit",
      "dataType": "bool"
    },
    {
      "name": "swapLimit",
      "dataType": "bool"
    },
    {
      "name": "kernelMemory",
      "dataType": "bool"
    },
    {
      "name": "kernelMemoryTCP",
      "dataType": "bool"
    },
    {
      "name": "cpuCfsPeriod",
      "dataType": "bool"
    },
    {
      "name": "cpuCfsQuota",
      "dataType": "bool"
    },
    {
      "name": "cpuShares",
      "dataType": "bool"
    },
    {
      "name": "cpuSet",
      "dataType": "bool"
    },
    {
      "name": "pidsLimit",
      "dataType": "bool"
    },
    {
      "name": "ipv4Forwarding",
      "dataType": "bool"
    },
    {
      "name": "bridgeNfIptables",
      "dataType": "bool"
    },
    {
      "name": "bridgeNfIp6tables",
      "dataType": "bool"
    },
    {
      "name": "debug",
      "dataType": "bool"
    },
    {
      "name": "oomKillDisable",
      "dataType": "bool"
    },
    {
      "name": "nGoroutines",
      "dataType": "int"
    },
    {
      "name": "systemTime",
      "dataType": "int"
    },
    {
      "name": "loggingDriver",
      "dataType": "str"
    },
    {
      "name": "nEventsListener",
      "dataType": "int"
    },
    {
      "name": "kernelVersion",
      "dataType": "str"
    },
    {
      "name": "operatingSystem",
      "dataType": "str"
    },
    {
      "name": "osType",
      "dataType": "str"
    },
    {
      "name": "architecture",
      "dataType": "str"
    },
    {
      "name": "indexServerAddress",
      "dataType": "str"
    },
    {
      "name": "nCpu",
      "dataType": "int"
    },
    {
      "name": "memTotal",
      "dataType": "int"
    },
    {
      "name": "genericResources",
      "dataType": "str"
    },
    {
      "name": "dockerRootDir",
      "dataType": "str"
    },
    {
      "name": "httpProxy",
      "dataType": "str"
    },
    {
      "name": "httpsProxy",
      "dataType": "str"
    },
    {
      "name": "noProxy",
      "dataType": "str"
    },
    {
      "name": "name",
      "dataType": "str",
      "required": true
    },
    {
      "name": "experimentalBuild",
      "dataType": "bool"
    },
    {
      "name": "serverVersion",
      "dataType": "str"
    },
    {
      "name": "clusterStore",
      "dataType": "str"
    },
    {
      "name": "clusterAdvertise",
      "dataType": "str"
    },
    {
      "name": "defaultRuntime",
      "dataType": "str"
    },
    {
      "name": "liveRestoreEnabled",
      "dataType": "bool"
    },
    {
      "name": "isolation",
      "dataType": "str"
    },
    {
      "name": "initBinary",
      "dataType": "str"
    },
    {
      "name": "warnings",
      "dataType": "str"
    }
  ]
}


{
  "probe": "dockerAgent",
  "check": "CheckContainers",
  "type": "containers",
  "metrics": [
    {
      "name": "id",
      "dataType": "str"
    },
    {
      "name": "name",
      "dataType": "str"
    },
    {
      "name": "names",
      "dataType": "str"
    },
    {
      "name": "image",
      "dataType": "str"
    },
    {
      "name": "imageId",
      "dataType": "str"
    },
    {
      "name": "command",
      "dataType": "str"
    },
    {
      "name": "created",
      "dataType": "int"
    },
    {
      "name": "state",
      "dataType": "str"
    },
    {
      "name": "status",
      "dataType": "str"
    },
    {
      "name": "networkMode",
      "dataType": "str"
    },
    {
      "name": "ports",
      "dataType": "str"
    }
  ]
}


{
  "probe": "dockerAgent",
  "check": "CheckContainers",
  "type": "networks",
  "metrics": [
    {
      "name": "name",
      "dataType": "str"
    },
    {
      "name": "networkId",
      "dataType": "str"
    },
    {
      "name": "endpointId",
      "dataType": "str"
    },
    {
      "name": "gateway",
      "dataType": "str"
    },
    {
      "name": "ipAddress",
      "dataType": "str"
    },
    {
      "name": "ipPrefixLen",
      "dataType": "int"
    },
    {
      "name": "ipv6Gateway",
      "dataType": "str"
    },
    {
      "name": "globalIpv6Address",
      "dataType": "str"
    },
    {
      "name": "MacAddress",
      "dataType": "str"
    },
    {
      "name": "driverOpts",
      "dataType": "str"
    },
    {
      "name": "aliases",
      "dataType": "str"
    },
    {
      "name": "links",
      "dataType": "str"
    },
    {
      "name": "ipamConfig",
      "dataType": "str"
    }
  ]
}


{
  "probe": "dockerAgent",
  "check": "CheckImages",
  "type": "images",
  "metrics": [
    {
      "name": "containers",
      "dataType": "int"
    },
    {
      "name": "created",
      "dataType": "int"
    },
    {
      "name": "name",
      "dataType": "str"
    },
    {
      "name": "parentId",
      "dataType": "str"
    },
    {
      "name": "repoDigests",
      "dataType": "str"
    },
    {
      "name": "repoTags",
      "dataType": "str"
    },
    {
      "name": "sharedSize",
      "dataType": "int"
    },
    {
      "name": "size",
      "dataType": "int"
    },
    {
      "name": "virtualSize",
      "dataType": "int"
    }
  ]
}

**Comment by joente** [comment]
For the `/containers/{id}/stats` , we only need memory and cpu.

Check: `CheckStats`
Type: `memory`
Item: derive from container name

Metrics:
- name: item-name
- percentUsed  (float)

Check: `CheckStats`
Type: `cpu`
Item: derive from container name

Metrics:
- name: item-name
- percentUsed  (float)

**Comment by riklempens** [comment]
Closing as we ported this agent to InfraSonar
